spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test1
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
mybatis:
      mapper-locations: classpath:mapper/**.xml
