spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: hhsj123456
mybatis:
      mapper-locations: classpath:mapper/**.xml
